package com.nexus.launcher.ui.backup

import com.google.gson.Gson
import com.google.gson.JsonObject
import com.nexus.launcher.data.FeedDao
import com.nexus.launcher.data.FeedSource
import com.nexus.launcher.locale.AppLocale
import com.nexus.launcher.locale.LocaleController
import com.nexus.launcher.theme.BackgroundLayerMode
import com.nexus.launcher.theme.CalmPalette
import com.nexus.launcher.theme.ColorBlindMode
import com.nexus.launcher.theme.ThemeController
import com.nexus.launcher.theme.ThemeMode
import com.nexus.launcher.typography.CustomFontEntry
import com.nexus.launcher.typography.FontFamilyController

/**
 * Round-trips the stores the manifest historically never touched: the Nexus theme engine
 * ([ThemeController]), typography ([FontFamilyController]) and app language
 * ([LocaleController]), plus the user's feed sources.
 *
 * These live in the same preferences DataStore as everything else but outside
 * [com.nexus.launcher.data.prefs.NexusSettingsData], so the settings snapshot cannot carry them —
 * they need their own manifest blocks.
 */
object BackupThemeState {

    private val gson = Gson()

    // ── Export ──────────────────────────────────────────────────────────────

    /**
     * The app's own language. Distinct from the device language: `AppLocale.SYSTEM` means "follow
     * the device", and any other value is an explicit in-app override that a backup should carry.
     */
    fun localeObject(locale: LocaleController): JsonObject = JsonObject().apply {
        addProperty("appLocale", locale.appLocale.value.tag)
    }

    suspend fun restoreLocale(locale: LocaleController, obj: JsonObject?) {
        if (obj == null) return
        val tag = obj.get("appLocale")?.takeIf { !it.isJsonNull }?.asString ?: return
        val target = AppLocale.fromTag(tag)
        // setAppLocale also re-applies AppCompatDelegate locales and repaints the widgets, so a
        // restore lands the language without needing a relaunch.
        if (target != locale.appLocale.value) runCatching { locale.setAppLocale(target) }
    }

    /** Theme mode (Dark / AMOLED / Calm / Automatic), Calm palette, background layer and a11y. */
    fun themeEngineObject(theme: ThemeController): JsonObject = JsonObject().apply {
        addProperty("themeMode", theme.themeMode.value.name)
        addProperty("calmPalette", theme.calmPalette.value.name)
        addProperty("backgroundLayerMode", theme.backgroundLayerMode.value.name)
        addProperty("colorBlindMode", theme.colorBlindMode.value.name)
        theme.notificationBadgeColor.value?.let { addProperty("notificationBadgeColor", it) }
    }

    /**
     * Font selection plus the user's imported fonts. [fontPathMapper] rewrites each entry's
     * on-disk path to the bundled asset path, so the files travel with the backup.
     */
    fun typographyObject(
        fonts: FontFamilyController,
        fontPathMapper: (CustomFontEntry) -> String?
    ): JsonObject = JsonObject().apply {
        addProperty("fontSelection", fonts.fontSelectionKey.value)
        add("customFonts", gson.toJsonTree(
            fonts.customFonts.value.map { entry ->
                mapOf(
                    "id" to entry.id,
                    "name" to entry.name,
                    // Relative asset path when bundled; the original otherwise.
                    "file" to (fontPathMapper(entry) ?: entry.filePath)
                )
            }
        ))
    }

    fun feedSourcesArray(sources: List<FeedSource>) = gson.toJsonTree(
        // The row id is autogenerated and meaningless on another install.
        sources.map { s ->
            mapOf(
                "title" to s.title,
                "url" to s.url,
                "category" to s.category,
                "isDefault" to s.isDefault,
                "isEnabled" to s.isEnabled,
                "sortOrder" to s.sortOrder
            )
        }
    )

    // ── Restore ─────────────────────────────────────────────────────────────

    /**
     * Applied last in the restore sequence: changing the theme mode re-themes every live surface,
     * so doing it before the layout and settings land would repaint against half-restored state.
     */
    suspend fun restoreThemeEngine(theme: ThemeController, obj: JsonObject?) {
        if (obj == null) return
        obj.get("themeMode")?.asString?.let { name ->
            runCatching { ThemeMode.valueOf(name) }.getOrNull()?.let { theme.setThemeMode(it) }
        }
        obj.get("calmPalette")?.asString?.let { name ->
            runCatching { CalmPalette.valueOf(name) }.getOrNull()?.let { theme.setCalmPalette(it) }
        }
        obj.get("backgroundLayerMode")?.asString?.let { name ->
            runCatching { BackgroundLayerMode.valueOf(name) }.getOrNull()
                ?.let { theme.setBackgroundLayerMode(it) }
        }
        obj.get("colorBlindMode")?.asString?.let { name ->
            runCatching { ColorBlindMode.valueOf(name) }.getOrNull()
                ?.let { theme.setColorBlindMode(it) }
        }
        theme.setNotificationBadgeColor(
            obj.get("notificationBadgeColor")?.takeIf { !it.isJsonNull }?.asString
        )
    }

    /**
     * @param resolveFontFile maps a manifest entry's `file` value to the restored on-disk path,
     *   or null when the font could not be unpacked — those entries are skipped so the picker
     *   never lists a font that cannot load.
     */
    suspend fun restoreTypography(
        fonts: FontFamilyController,
        obj: JsonObject?,
        resolveFontFile: (String) -> String?
    ) {
        if (obj == null) return
        obj.getAsJsonArray("customFonts")?.forEach { element ->
            val e = element.asJsonObject
            val id = e.get("id")?.asString ?: return@forEach
            val name = e.get("name")?.asString ?: return@forEach
            val path = e.get("file")?.asString?.let(resolveFontFile) ?: return@forEach
            runCatching { fonts.addCustomFont(CustomFontEntry(id, name, path)) }
        }
        // After the fonts exist, so selecting a restored custom font resolves.
        obj.get("fontSelection")?.asString?.let { runCatching { fonts.setFontSelection(it) } }
    }

    /**
     * Merged by URL rather than replaced: the launcher seeds a curated set on first run, and a
     * blind insert would leave the user with two of each.
     *
     * A restored feed has sources but no articles — article bodies are not backed up — so the
     * page is empty until something fetches. Neither the last-refresh stamp nor a change in the
     * source set is a reliable signal for that: on a fresh install the defaults are already
     * seeded when the restore runs, so every restored URL is a duplicate and nothing changes.
     * The pending flag says so outright, and the controller consumes it once.
     */
    suspend fun restoreFeedSources(
        dao: FeedDao,
        sources: com.google.gson.JsonArray?,
        context: android.content.Context? = null
    ) {
        if (sources == null) return
        val existing = runCatching { dao.getAllSourcesSnapshot() }.getOrDefault(emptyList())
        val known = existing.map { it.url.trim().lowercase() }.toSet()
        val additions = sources.mapNotNull { element ->
            val o = element.asJsonObject
            val url = o.get("url")?.asString?.takeIf { it.isNotBlank() } ?: return@mapNotNull null
            if (url.trim().lowercase() in known) return@mapNotNull null
            FeedSource(
                title = o.get("title")?.asString ?: url,
                url = url,
                category = o.get("category")?.asString ?: "",
                isDefault = o.get("isDefault")?.asBoolean ?: false,
                isEnabled = o.get("isEnabled")?.asBoolean ?: true,
                sortOrder = o.get("sortOrder")?.asInt ?: 0
            )
        }
        if (additions.isNotEmpty()) runCatching { dao.insertSources(additions) }
        if (context != null) {
            runCatching {
                context.getSharedPreferences(
                    com.nexus.launcher.feed.NexusFeedTimeRefreshHelper.PREFS_NAME,
                    android.content.Context.MODE_PRIVATE
                ).edit()
                    .remove("last_refresh_time")
                    .putBoolean(
                        com.nexus.launcher.feed.NexusFeedTimeRefreshHelper.KEY_PENDING_RESTORE_REFRESH,
                        true
                    )
                    .apply()
            }
        }
    }
}
